config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/new'
  get 'reviews/delete'
  get 'reviews/edit'
  get 'reviews/update'

  root to: "pages#home"
  resources :cocktails do
    resources :doses, except: [:show, :destroy]
    resources :reviews, except: [:show, :index]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cokctails
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  accepts_nested_attributes_for :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: [:cocktail] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates_numericality_of :rating, greater_than_or_equal_to: 0, less_than_or_equal_to: 5
  validates :cocktail, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
    @cocktail.doses.build
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail =Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :category, :how_to_mix, doses_attributes: [:description, :cocktail_id, :ingredient_id],
                                     reviews_attributes: [:content, :rating, :cocktail_id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:edit, :destroy]
  before_action :set_cocktail, only: [:new, :create]

  def index
  end

  def new
    @dose = Dose.new
  end

  def edit
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient, :ingredient_id, :cocktail_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @cocktails = Cocktail.order('id DESC').limit(4)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_cocktail, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @review.destroy
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<div class="row full-page-form">
  <div class="col-sm-12 col-md-8 offset-md-2">

    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.input :category %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.simple_fields_for :doses do |d| %>
        <%= d.association :ingredient %>
        <%= d.input :description %>
      <% end %>
      <%= f.input :how_to_mix %>
      <% if @cocktail.name %>
        <%= f.submit "Edit Cocktail", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Add Cocktail", class: "btn btn-primary" %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Mr. Cocktail</h1>
    <p>Make Incredible Cocktails to Impress your Friends</p>
  </div>
</div>

<div class="wrapper">
  <div class="container">

    <% @cocktails.each_with_index do |cocktail, index| %>
      <% if index % 3 == 0 && index != 0 %>
        </div>
      <% end %>

      <% if index % 3 == 0 %>
        <div class="row">
      <% end %>

      <div class="col-sm-12 col-md-6 col-xl-4">
        <%= link_to cocktail do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path cocktail.photo %>');">
            <div class="card-filter">
              <div class="card-description">
                <h2><%= cocktail.name %></h2>
              </div>
              <div class="card-info">
                <ul>
                  <% cocktail.doses.each do |dose| %>
                    <li><%= dose.ingredient.name %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <% if index == @cocktails.length - 1 %>

        </div>

      <% end %>
    <% end %>

  </div>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>
<%= render 'form', cocktail: @cokctail %>

app/views/cocktails/show.html.erb
<div class="cocktail-show-container">

  <div class="row">
    <div class="col-xs-12 col-xl-5">
      <div class="cocktail-image" style="background-image: url('<%=  cl_image_path @cocktail.photo %>');">
      </div>
    </div>

    <div class="col-xs-12 col-xl-7">
      <div class="cocktail-info">
        <h1><%= @cocktail.name %>
          <%= link_to new_cocktail_dose_path(@cocktail) do %>
            <small><a data-toggle="modal" data-target="#edit-modal" data-whatever="@mdo"><i class="far fa-edit"></i></a></small>
            <small>
              <%= link_to "<i class='delete-btn fas fa-trash'></i>".html_safe, @cocktail,
                method: :delete,
                data: { confirm: "Are you sure?" } %></small>
          <% end %>
        </h1>
        <ul>
          <% @cocktail.doses.each do |dose| %>
            <li>
              <h5><%= dose.ingredient.name %></h5>
              <p><%= dose.description %></p>
            </li>
          <% end %>
          <div class="collapsable">
            <h5><i class="fas fa-plus"></i>  New dose!</h5>
          </div>
          <div class="hidden-content absolute">
            <%= render 'doses/form', dose: @dose, cocktail: @cocktail %>
          </div>
        </ul>
      </div>
    </div>
  </div>

  <h2>Reviews</h2>
  <% @cocktail.reviews.each do |r| %>

    <div class="review">
      <div class="stars">
        <h4><% r.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %></h4>
      </div>
      <div class="review-contetn">
        <p><%= r.content %></p>
      </div>
    </div>
  <% end %>

  <div class="collapsable">
    <h5>Comment!</h5>
  </div>
  <div class="hidden-content">
    <%= render 'reviews/form', review: @review, cocktail: @cocktail %>
  </div>

</div>


<div class="modal fade" id="edit-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-adjust">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Dose</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= render 'form', cocktail: @cocktail %>

      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit "Add Dose", class: "btn btn-primary" %>
<% end %>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>
<%= render 'form', dose: @dose, cocktail: @cocktail %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>


    <%= render 'shared/navbar' %>

    <% unless current_page?(:root) %>

      <div class="wrapper">
        <div class="container">

    <% end %>

    <%= yield %>

    <% unless current_page?(:root) %>

        </div>
      </div>

    <% end %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="wrapper">
  <div class="container home">
    <div class="row responsive-sm">


      <div class="col-xs-12 col-sm-6 col-lg-3">
        <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1517093911940-08cb5b3952e7?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=101c26932078be8b5fc48798d5b3f710&auto=format&fit=crop&w=683&q=80');">
          <div class="category-content">
            <h3>Start Browsing</h3>
          </div>
        </div>
      </div>
    </div>

    <%= render 'shared/categories' %>

    <h2>
      Latest Cocktails
    </h2>

    <%= render 'shared/display_cocktails_cards' %>

  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Add review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Mr. Cocktail</h1>
    <p>Make, share and explore incredible cocktails</p>
  </div>
</div>

app/views/shared/_categories.html.erb
<h2 class="padding-top-title">
  Categories
  <span class="responsive-sm-hide"> |
    <small>
      <%= link_to cocktails_url do %>
        Go to All <i class="fas fa-angle-right"></i>
      <% end %>
    </small>
  </span>
</h2>
<div class="categories">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-lg-3">
      <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1517093911940-08cb5b3952e7?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=101c26932078be8b5fc48798d5b3f710&auto=format&fit=crop&w=683&q=80');">
        <div class="category-content">
          <h3>Refreshing</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-3">
      <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/141815/pexels-photo-141815.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
        <div class="category-content">
          <h3>Sweet</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-3">
      <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1458995511454-37bbe550c3f6?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e98f0be116d30fd71bb628db61e11a0d&auto=format&fit=crop&w=1867&q=80');">
        <div class="category-content">
          <h3>Bitter</h3>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-3">
      <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/357577/pexels-photo-357577.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
          <h3>Sour</h3>
      </div>
    </div>
  </div>
</div>

app/views/shared/_display_cocktails_cards.html.erb
<div class="categories">
  <div class="row">
    <% @cocktails.each do |cocktail| %>

      <div class="col-xs-12 col-sm-6 col-lg-3">

        <%= link_to cocktail do %>
          <div class="my-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path cocktail.photo %>');">
            <div class="my-card-content">
              <h2><%= cocktail.name %></h2>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="wrapper">
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Website made by Danilo Condo
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="my-nav">
  <%= link_to :root, class: "logo" do %>
    <i class="fas fa-glass-martini"><span>Mr. Cocktail</span></i>
  <% end %>
  <%= link_to "New Cocktail", new_cocktail_path %>
</nav>


<!--
 <div class="nav-collapse">
    <a class="collapsable">
      <i class="fas fa-bars"></i>
    </a>
    <ul class="hidden-content">
      <li><%#= link_to "New Cocktail", new_cocktail_path, class: "nav-link" %></li>
    </ul>
  </div> -->